[package]
name = "vt6tokio"
version = "0.0.1"
authors = ["Stefan Majewsky <majewsky@gmx.net>"]

[dependencies]
log = ">= 0.4"

futures   = "^0.1.18"
tokio     = "^0.1.7"
tokio-uds = "^0.2.0"

[dependencies.vt6]
version = "0.0.1"
path    = "../vt6"
